#!/usr/bin/bash
#!/bin/bash

# To initialize a project
yo_init() {
  # Create .yo directory in home if does not exist
  mkdir -p "$HOME/.yo"

  _yoInitPath=$(pwd)
  _projectConfigDirName=${_yoInitPath////_}

  # Creates a project config directory if does not exist
  # Sub directories under initialized directory cannot be initialized
  yo_get_project_info
  if [ -d "$HOME/.yo/$_projectConfigDirName" ] || [[ -n "$currentProjectRoot" ]]; then
    unset currentProjectRoot
    printError "Project already initialized"
  else
    mkdir "$HOME/.yo/$_projectConfigDirName"
    echo "project_root=$(pwd)/" >"$HOME/.yo/$_projectConfigDirName/config"
    echo "script_path=" >>"$HOME/.yo/$_projectConfigDirName/config"
    echo "package_path=" >>"$HOME/.yo/$_projectConfigDirName/config"

    printSuccess "Project initialized"
  fi
}

# To set the path to bash scripts
# Path should be relative to project root
yo_script() {
  yo_verify_project_initialization

  sed -i 's|script_path=.*|script_path='"$currentProjectRoot$1"'|g' "$HOME/.yo/$currentProjectFolderName"/config
  unset currentProjectRoot
  unset currentProjectFolderName
}

# To set the path to flutter package(s)
# Path should be relative to project root
yo_package() {
  yo_verify_project_initialization

  sed -i 's|package_path=.*|package_path='"$currentProjectRoot$1"'|g' "$HOME/.yo/$currentProjectFolderName"/config
  unset currentProjectRoot
  unset currentProjectFolderName
}

# Run `flutter pub get` on specified package. If no package is specified, `flutter pub get` will be run on all packages
yo_get() {
  yo_verify_project_initialization

  _currentFolder=$(pwd)

  shopt -s nullglob

  _currentProjectPackage=$(grep -oP "(package_path=\K.*)" "$HOME/.yo/$currentProjectFolderName"/config)
  unset currentProjectFolderName
  unset currentProjectRoot

  # Print error if package path has not been set
  if [ -z "$_currentProjectPackage" ]; then
    printError "Please add package path first"
    return
  fi

  cd "$_currentProjectPackage" || return

  if [ -n "$1" ]; then
    if [ -d "$1" ]; then
      yo_flutter_command "$1" "flutter pub get"
    else
      printError "No such directory"
    fi
  else
    _directories=(*)
    for _d in "${_directories[@]}"; do
      yo_flutter_command "$_d" "flutter pub get"
    done
  fi

  cd "$_currentFolder" || return
}

# Run `flutter test` on specified package. If no package is specified, `flutter test` will be run on all packages
yo_test() {
  yo_verify_project_initialization

  _currentFolder=$(pwd)

  shopt -s nullglob

  _currentProjectPackage=$(grep -oP "(package_path=\K.*)" "$HOME/.yo/$currentProjectFolderName"/config)
  unset currentProjectFolderName
  unset currentProjectRoot

  # Print error if package path has not been set
  if [ -z "$_currentProjectPackage" ]; then
    printError "Please add package path first"
    return
  fi

  cd "$_currentProjectPackage" || return

  if [ -n "$1" ]; then
    if [ -d "$1" ]; then
      yo_flutter_command "$1" "flutter test"
    else
      printError "No such directory"
    fi
  else
    _directories=(*)
    for _d in "${_directories[@]}"; do
      yo_flutter_command "$_d" "flutter test"
    done
  fi

  cd "$_currentFolder" || return
}

yo() {
  cmd=$1
  path=$2

  case $cmd in
  init)
    yo_init
    ;;
  script)
    yo_script "$path"
    ;;
  package)
    yo_package "$path"
    ;;
  get)
    yo_get "$path"
    ;;
  test)
    yo_test "$path"
    ;;
  esac
}

# Save the current project root in currentProjectRoot variable and current project folder name in currentProjectFolderName variable
yo_get_project_info() {
  _currentPath=$(pwd)
  _currentPathName=${_currentPath////_}

  shopt -s nullglob

  cd "$HOME/.yo/" || return

  _directories=(*)
  for _dir in "${_directories[@]}"; do
    if [[ $_currentPathName == *"$_dir"* ]]; then
      cd "$_currentPath" || return

      currentProjectFolderName="$_dir"
      currentProjectRoot=$(grep -oP "(project_root=\K.*)" "$HOME/.yo/$currentProjectFolderName"/config)
      return
    fi
  done
  cd "$_currentPath" || return
}

# Verify if project has been initialized
yo_verify_project_initialization() {
  yo_get_project_info

  if [ -z "$currentProjectRoot" ]; then
    unset currentProjectRoot
    printError "Project has not yet been initialized"
    return
  fi
}

yo_flutter_command() {
  cd "$1" || return
  _pubspec_file=pubspec.yaml
  if [ -f "$_pubspec_file" ]; then
    eval "$2"
  fi
  cd ..
}

# Color codes
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'

printError() {
  echo -e "${RED}*** $1 ***"
}

printSuccess() {
  echo -e "${GREEN}*** $1 ***"
}

printInfo() {
  echo -e "${YELLOW}*** $1 ***"
}
