#!/usr/bin/env bash

#Global variables
# Where project was initialized
configPath=
# Flag if project has been initialized
projectInitialized=
# Where yo commands is being triggered from
workingDirectory=

# Initialize a project if has not been
# Sub directories under initialized directory cannot be initialized
yo_init() {
  get_project_info
  if $projectInitialized; then
    printError "Project already initialized"
  else
    # Create a .yo directory in current directory if it does not exist
    mkdir -p ".yo"
    printSuccess "Project initialized"
  fi
}

# Add extension scripts to YO
yo_add() {
  echo "adding"
}

yo() {
  local _cmd=$1
  local _path=$2

  unset commandMap
  declare -A commandMap=(["add"]="1")

  if [[ -n "$_cmd" ]]; then
    if [[ -n "${commandMap[$_cmd]}" ]]; then
      get_project_info
      if ! $projectInitialized; then
        printError "Project has not yet been initialized"
        return
      fi
    fi
  fi

  if [[ -z "$_cmd" ]]; then
    echo "show help"
  else
    case $_cmd in
    init)
      yo_init
      ;;
    add)
      yo_add "$_path"
      ;;
    *)
      printError "Unknown sub-command"
      ;;
    esac
  fi
}

# ------------------------------ Helper ------------------------------

# Save the project root in `projectRoot` variable
get_project_info() {
  clean_global_variables

  workingDirectory=$(pwd)
  get_config
  go_back
}

# Go back until `.yo` is found and set `projectRoot`
get_config() {
  projectInitialized=false
  if [ -d ".yo" ]; then
    projectInitialized=true
    if [ -e ".yo/config" ]; then
      configPath="$(pwd)/.yo/config"
    fi
  else
    if [ "$(dirname "$(pwd)")" != "/" ]; then
      cd ..
      get_config
    fi
  fi
}

# Go back to directory where yo command was fired from
go_back() {
  cd "$workingDirectory" || return
}

# Unset global variables
clean_global_variables() {
  unset configPath
  unset projectInitialized
}

# Color codes
_ERROR='\033[1;31m'
_SUCCESS='\033[1;32m'
_YELLOW='\033[1;33m'
_NO_COLOR='\033[0m'

printError() {
  echo -e "${_ERROR}*** $1 ***${_NO_COLOR}"
}

printSuccess() {
  echo -e "${_SUCCESS}*** $1 ***${_NO_COLOR}"
}

printInfo() {
  echo -e "${_YELLOW}*** $1 ***${_NO_COLOR}"
}

print() {
  echo -e "${_NO_COLOR}$1"
}

# Need this for later

# get value from config
## projectRoot=$(grep "project_root" "config" | cut -d "=" -f 2)

# set value in config
## echo "project_root=$(pwd)/" >>".yo/config"
